#!/usr/bin/env python3
"""
Create the media bucket and apply its access policy.

The policy is not written here. It is generated by media_rules.bucket_policy()
from the same purpose taxonomy the service uses to decide what is confidential,
so a purpose added to the taxonomy cannot end up with a bucket that disagrees
about whether the world may read it. That is the whole reason this script
imports from the service instead of carrying its own JSON.

Idempotent: safe to run against a bucket that already exists, and re-applying
the policy is how a taxonomy change gets rolled out.

    python scripts/bootstrap_storage.py            # apply
    python scripts/bootstrap_storage.py --verify   # report, change nothing
"""

import importlib.util
import json
import os
import sys
from pathlib import Path

import boto3
from botocore.client import Config
from botocore.exceptions import ClientError

ROOT = Path(__file__).resolve().parent.parent

# Loaded by path rather than imported as a package: the services are not on
# sys.path and are not meant to be. Same approach the media unit tests use.
_spec = importlib.util.spec_from_file_location(
    "media_rules",
    ROOT / "services" / "media-service" / "app" / "services" / "media_rules.py")
media_rules = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(media_rules)

ENDPOINT = os.getenv("S3_BOOTSTRAP_ENDPOINT_URL",
                     os.getenv("S3_PUBLIC_ENDPOINT_URL", "http://localhost:9000"))
BUCKET = os.getenv("S3_BUCKET", media_rules.DEFAULT_BUCKET)
ACCESS_KEY = os.getenv("S3_ACCESS_KEY") or os.getenv("MINIO_ROOT_USER")
SECRET_KEY = os.getenv("S3_SECRET_KEY") or os.getenv("MINIO_ROOT_PASSWORD")


def client():
    if not ACCESS_KEY or not SECRET_KEY:
        sys.exit("S3_ACCESS_KEY/S3_SECRET_KEY (or MINIO_ROOT_USER/PASSWORD) "
                 "must be set. Rule 8: no default credentials.")
    return boto3.client(
        "s3",
        endpoint_url=ENDPOINT,
        aws_access_key_id=ACCESS_KEY,
        aws_secret_access_key=SECRET_KEY,
        config=Config(signature_version="s3v4", s3={"addressing_style": "path"}),
        region_name=os.getenv("S3_REGION", "us-east-1"),
    )


def ensure_bucket(s3) -> bool:
    """Returns True if it had to be created."""
    try:
        s3.head_bucket(Bucket=BUCKET)
        return False
    except ClientError as e:
        if e.response["Error"]["Code"] not in ("404", "NoSuchBucket"):
            raise
    s3.create_bucket(Bucket=BUCKET)
    return True


def main() -> int:
    verify_only = "--verify" in sys.argv
    s3 = client()

    policy = media_rules.bucket_policy(BUCKET)
    public = sorted(media_rules.public_prefixes())
    confidential = sorted(media_rules.confidential_prefixes())

    print(f"endpoint     {ENDPOINT}")
    print(f"bucket       {BUCKET}")
    print(f"public       {public}")
    print(f"confidential {confidential}  (no policy statement -- default deny)")

    # A prefix that is somehow in both lists would mean the taxonomy is
    # self-contradictory, and the bucket would be the place it hurts.
    overlap = set(public) & set(confidential)
    if overlap:
        sys.exit(f"FATAL: prefixes are both public and confidential: {overlap}")

    if verify_only:
        try:
            live = json.loads(s3.get_bucket_policy(Bucket=BUCKET)["Policy"])
        except ClientError as e:
            print(f"no policy on the bucket ({e.response['Error']['Code']})")
            return 1
        if live == policy:
            print("policy MATCHES the taxonomy")
            return 0
        print("policy DRIFTED from the taxonomy")
        print("  live:     ", json.dumps(live, sort_keys=True))
        print("  generated:", json.dumps(policy, sort_keys=True))
        return 1

    if ensure_bucket(s3):
        print(f"created bucket {BUCKET}")
    else:
        print(f"bucket {BUCKET} already exists")

    s3.put_bucket_policy(Bucket=BUCKET, Policy=json.dumps(policy))
    print("policy applied:")
    for resource in policy["Statement"][0]["Resource"]:
        print(f"  anonymous s3:GetObject on {resource}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
